version: '3.8'

services:
  mongo:
    image: mongo
    container_name: sparrow-connected-mongodb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb_network
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: sparrow-connected-server-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: sparrow-connected-mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    networks:
      - mongodb_network
    links:
      - mongo

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb-data:
